// <auto-generated />
using System;
using AttendanceTask.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceTask.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20250117050115_Attendancedbadded")]
    partial class Attendancedbadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceTask.Models.Admin", b =>
                {
                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("userName");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("userPassword");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("AttendanceTask.Models.Attendance", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("empId");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("empName");

                    b.Property<TimeOnly?>("InTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasColumnName("inTime")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<TimeOnly?>("OutTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasColumnName("outTime")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("EmpId")
                        .HasName("PK__attendan__AFB3EC0D70B67406");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("AttendanceTask.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("empId");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("empName");

                    b.HasKey("EmpId")
                        .HasName("PK__employee__AFB3EC0DBACBDA35");

                    b.ToTable("employees", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
